authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('register/', user_register, name='user_register'),
    
    path('flutter/login/', flutter_login, name='flutter_login'),
    path('flutter/register/', flutter_register, name='flutter_register'),
    path('flutter/logout/', flutter_logout, name='flutter_logout'),
]

forum_diskusi/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import forum_index, get_forum_by_id,get_post_comments, get_resto,  get_user, get_forum, get_username, post_create, comment_create_flutter, post_create_flutter, post_detail, post_update, post_delete, upvote_post, downvote_post, post_comment, comment_edit, comment_delete, vote_forum
from . import views

app_name = 'forum_diskusi'

urlpatterns = [
    path('', forum_index, name='forum_index'),
    path('get-username/<int:id>', get_username, name='get_username'),
    path('get-resto/<int:id>', get_resto, name='get_resto'),
    path('post/new/', post_create, name='post_create'),
    path('post/get-all/', get_forum, name='get_forum'),
    path('post/get-<int:id>/', get_forum_by_id, name='get_forum_by_id'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', post_update, name='post_update'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('upvote/<int:post_id>/', upvote_post, name='post_upvote'),
    path('downvote/<int:post_id>/', downvote_post, name='post_downvote'),
    path('comment/<int:post_id>/', post_comment, name='post_comment'),
    path('comment/<int:pk>/edit/', comment_edit, name='comment_edit'),
    path('comment/<int:pk>/delete/', comment_delete, name='comment_delete'),
    path('post/new-flutter/', post_create_flutter, name='post_create_flutter'),
    path('post/new-comment/', comment_create_flutter, name='comment_create_flutter'),
    path('get-user/', get_user, name='get_user'),
    path('post/<int:pk>/comments/', get_post_comments, name='get_post_comments'),
    path('vote-forum/', vote_forum, name='vote_forum'),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import *

app_name = 'main'
urlpatterns = [
    path('', main_page, name='main_page'),
    path('show-json/', show_json, name='show_json'),

    path('steakhouse/<int:pk>/', steakhouse_page, name='steakhouse_page'),

    path('forum_diskusi/', include('forum_diskusi.urls', namespace='forum_diskusi')),
    path('about/', about_page, name='about_page'),    
]

steve/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('resto/', include('resto.urls', namespace='resto')),
    path('forum/', include('forum_diskusi.urls', namespace='forum_diskusi')),
    path('wishlist/', include(('wishlist.urls', 'wishlist'), namespace='wishlist')), 
    path('auth/', include('authentication.urls')),
    path('rating/', include('resto_rating.urls', namespace='resto_rating')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', view_wishlists, name='view_wishlists'),
    path('edit/<int:id>/', edit_wishlist, name='edit_wishlist'),
    path('delete/<int:id>/', delete_wishlist, name='delete_wishlist'),
    path('delete-category/<int:id>/', delete_category, name='delete_category'),
    
    path('add/<int:restaurant_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('fetch-user-categories/', fetch_user_categories, name='fetch_user_categories'),

    path('add-flutter/', add_to_wishlist_flutter, name='add_to_wishlist_flutter'),
    path('json/', show_json, name='show_json'),
    path('edit-flutter/', edit_flutter, name='edit_flutter'),
    path('delete-flutter/', delete_flutter, name='delete_flutter'),
    path('delete-category-flutter/', delete_category_flutter, name='delete_category_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script 
    src="https://cdn.tailwindcss.com">
        :root {
            --primary-red: #B22222;
            --cream: #F5F5DC;
        }</script>
    <link rel="stylesheet" href="/static/css/global.css">
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="bg-red-600 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl md-10 mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <h1 class="text-xl sm:text-2xl font-bold text-krem">Steve SteakHouse</h1>
      </div>
      <div class="hidden md:flex items-center">
        <span class="text-krem py-2 px-4 mr-2">Welcome, {{user}}</span>
        <a href="{% url 'main:main_page' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Home  
        </a>
        <a href="{% url 'wishlist:view_wishlists' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Wishlist
        </a>
        <a href="{% url 'forum_diskusi:forum_index' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Forum
        </a>
        <a href="/about" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Contact
        </a>
        <a href="{% url 'authentication:user_logout' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Logout
        </a>
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-krem" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden px-4 w-full transition-all duration-300 ease-in-out">
    <div class="pt-2 pb-3 space-y-1">
      <span class="block text-krem py-2 mr-2">Welcome, {{user}}</span>
      <a href="{% url 'main:main_page' %}" class="block text-krem py-2">Home</a>
      <a href="{% url 'wishlist:view_wishlists' %}" class="block text-krem py-2">Wishlist</a>
      <a href="{% url 'forum_diskusi:forum_index' %}" class="block text-krem py-2">
        Forum
      </a>
      <a href="/about" class="block text-krem py-2">Contact</a>
      <a href="{% url 'authentication:user_logout' %}" class="block text-center bg-red-500 hover:bg-red-700 text-krem font-bold py-2 transition rounded duration-300">Logout</a>
    </div>
  </div>
</nav>

<script>
  const btn = document.querySelector("button.mobile-menu-button");
  const menu = document.querySelector(".mobile-menu");

  btn.addEventListener("click", () => {
    menu.classList.toggle("hidden");
  });
</script>