authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('register/', user_register, name='user_register'),
    
    path('flutter/login/', flutter_login, name='flutter_login'),
    path('flutter/register/', flutter_register, name='flutter_register'),
    path('flutter/logout/', flutter_logout, name='flutter_logout'),
]

forum_diskusi/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import forum_index, get_forum_by_id,get_post_comments, get_resto,  get_user, get_forum, get_username, post_create, comment_create_flutter, post_create_flutter, post_detail, post_update, post_delete, upvote_post, downvote_post, post_comment, comment_edit, comment_delete, vote_forum
from . import views

app_name = 'forum_diskusi'

urlpatterns = [
    path('', forum_index, name='forum_index'),
    path('get-username/<int:id>', get_username, name='get_username'),
    path('get-resto/<int:id>', get_resto, name='get_resto'),
    path('post/new/', post_create, name='post_create'),
    path('post/get-all/', get_forum, name='get_forum'),
    path('post/get-<int:id>/', get_forum_by_id, name='get_forum_by_id'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', post_update, name='post_update'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('upvote/<int:post_id>/', upvote_post, name='post_upvote'),
    path('downvote/<int:post_id>/', downvote_post, name='post_downvote'),
    path('comment/<int:post_id>/', post_comment, name='post_comment'),
    path('comment/<int:pk>/edit/', comment_edit, name='comment_edit'),
    path('comment/<int:pk>/delete/', comment_delete, name='comment_delete'),
    path('post/new-flutter/', post_create_flutter, name='post_create_flutter'),
    path('post/new-comment/', comment_create_flutter, name='comment_create_flutter'),
    path('get-user/', get_user, name='get_user'),
    path('post/<int:pk>/comments/', get_post_comments, name='get_post_comments'),
    path('vote-forum/', vote_forum, name='vote_forum'),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import *

app_name = 'main'
urlpatterns = [
    path('', main_page, name='main_page'),
    path('show-json/', show_json, name='show_json'),

    path('steakhouse/<int:pk>/', steakhouse_page, name='steakhouse_page'),

    path('forum_diskusi/', include('forum_diskusi.urls', namespace='forum_diskusi')),
    path('about/', about_page, name='about_page'),    
]

steve/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('resto/', include('resto.urls', namespace='resto')),
    path('forum/', include('forum_diskusi.urls', namespace='forum_diskusi')),
    path('wishlist/', include(('wishlist.urls', 'wishlist'), namespace='wishlist')), 
    path('auth/', include('authentication.urls')),
    path('rating/', include('resto_rating.urls', namespace='resto_rating')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', view_wishlists, name='view_wishlists'),
    path('edit/<int:id>/', edit_wishlist, name='edit_wishlist'),
    path('delete/<int:id>/', delete_wishlist, name='delete_wishlist'),
    path('delete-category/<int:id>/', delete_category, name='delete_category'),
    
    path('add/<int:restaurant_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('fetch-user-categories/', fetch_user_categories, name='fetch_user_categories'),

    path('add-flutter/', add_to_wishlist_flutter, name='add_to_wishlist_flutter'),
    path('json/', show_json, name='show_json'),
    path('edit-flutter/', edit_flutter, name='edit_flutter'),
    path('delete-flutter/', delete_flutter, name='delete_flutter'),
    path('delete-category-flutter/', delete_category_flutter, name='delete_category_flutter'),
]

main/forms.py
from django.forms import ModelForm
from resto.models import Restaurant 
from reservation.models import Reservation

class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        fields = ["name", "location", "price", "special_menu","description", "opening_time", "closing_time"]

class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['name', 'date', 'time', 'number_of_guests', 'contact_info', 'special_request', 'status']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core import serializers
from django.views.decorators.http import require_POST
import json

# Models
from resto.models import Restaurant
from resto_rating.models import Review
from reservation.models import Reservation
from wishlist.models import WishlistCategory, WishlistItem

@login_required(login_url='authentication:user_login')
def main_page(request):
    restaurants = Restaurant.objects.all()
    context = {
        'user': request.user,
        'restaurants': restaurants,
    }
    return render(request, 'main/main_page.html', context)

def about_page(request):
    return render(request, 'main/about_page.html')

def show_json(request):
    restaurants = Restaurant.objects.all()
    return HttpResponse(serializers.serialize("json", restaurants), content_type="application/json")

def show_json_by_id(request, id):
    restaurant = Restaurant.objects.get(id=id)
    return HttpResponse(serializers.serialize("json", restaurant), content_type="application/json")
    
@login_required(login_url='authentication:user_login')
def steakhouse_page(request, pk):
    steakhouse = get_object_or_404(Restaurant, id=pk)
    reviews = Review.objects.filter(restaurant=steakhouse)
    reservations = Reservation.objects.filter(user=request.user, restaurant=steakhouse)

    user_has_reviewed = False
    if request.user.is_authenticated:
        user_has_reviewed = Review.objects.filter(restaurant=steakhouse, user=request.user).exists()

    context = {
        'steakhouse': steakhouse,
        'reviews': reviews,
        'reservations': reservations,
        'user_has_reviewed': user_has_reviewed,
    }
    return render(request, 'main/steakhouse_page.html', context)

main/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div id="login-page" class="flex justify-center items-center min-h-screen px-4 py-10 bg-cover bg-center">
    <div class="login-box bg-white bg-opacity-60 p-8 rounded shadow-md w-full sm:w-2/3 md:w-1/2 lg:w-1/3 h-auto backdrop-blur-sm">
        <h1 class="text-2xl sm:text-3xl font-bold mb-4 text-center">Login</h1>
        <form method="POST">
            {% csrf_token %}

            <div class="mb-4">
                <label for="username" class="block text-gray-700 font-medium">Username</label>
                <input type="text" name="username" id="username" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" required>
            </div>

            <div class="mb-4">
                <label for="password" class="block text-gray-700 font-medium">Password</label>
                <input type="password" name="password" id="password" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" required>
            </div>

            <button type="submit" class="w-full bg-red-500 text-white py-2 sm:py-3 rounded-lg hover:bg-red-600 transition duration-300">Login</button>

            {% if form.errors %}
            <div class="error-messages bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mt-4">
                Please enter a correct username and password. Note that both fields may be case-sensitive.
            </div>
            {% endif %}
        </form>

        <p class="text-center text-gray-600 mt-6">Don't have an account? 
            <a href="{% url 'main:user_register' %}" class="text-red-500 hover:underline">Sign up</a>
        </p>
        
    </div>
</div>
{% endblock content %}

main/templates/navbar.html
<nav class="bg-red-600 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl md-10 mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <h1 class="text-xl sm:text-2xl font-bold text-krem">Steve SteakHouse</h1>
      </div>
      <div class="hidden md:flex items-center">
        <span class="text-krem py-2 px-4 mr-2">Welcome, {{user}}</span>
        <a href="{% url 'main:main_page' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Home  
        </a>
        <a href="{% url 'wishlist:view_wishlists' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Wishlist
        </a>
        <a href="{% url 'forum_diskusi:forum_index' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Forum
        </a>
        <a href="/about" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Contact
        </a>
        <a href="{% url 'main:user_logout' %}" class="hover:bg-red-700 text-krem py-2 px-4 transition rounded duration-300 mr-2">
          Logout
        </a>
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-krem" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden px-4 w-full transition-all duration-300 ease-in-out">
    <div class="pt-2 pb-3 space-y-1">
      <span class="block text-krem py-2 mr-2">Welcome, {{user}}</span>
      <a href="{% url 'main:main_page' %}" class="block text-krem py-2">Home</a>
      <a href="{% url 'wishlist:view_wishlists' %}" class="block text-krem py-2">Wishlist</a>
      <a href="{% url 'forum_diskusi:forum_index' %}" class="block text-krem py-2">
        Forum
      </a>
      <a href="/about" class="block text-krem py-2">Contact</a>
      <a href="{% url 'main:user_logout' %}" class="block text-center bg-red-500 hover:bg-red-700 text-krem font-bold py-2 transition rounded duration-300">Logout</a>
    </div>
  </div>
</nav>

<script>
  const btn = document.querySelector("button.mobile-menu-button");
  const menu = document.querySelector(".mobile-menu");

  btn.addEventListener("click", () => {
    menu.classList.toggle("hidden");
  });
</script>

main/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div id="register-page" class="flex justify-center items-center min-h-screen px-4 py-10 bg-cover bg-center">
    <div class="login-box bg-white bg-opacity-60 p-8 rounded shadow-md w-full sm:w-2/3 md:w-1/2 lg:w-1/3 h-auto backdrop-blur-sm">
        <h1 class="text-2xl sm:text-3xl font-bold mb-4 text-center">Register</h1>
        <form method="POST">
            {% csrf_token %}

            <div class="mb-4">
                <label for="username" class="block text-gray-700 font-medium">Username</label>
                <input type="text" name="username" id="username" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" placeholder="Enter your username" required>
            </div>

            <div class="mb-4">
                <label for="password1" class="block text-gray-700 font-medium">Password</label>
                <input type="password" name="password1" id="password1" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" placeholder="Enter your password" required>
            </div>

            <div class="mb-4">
                <label for="password2" class="block text-gray-700 font-medium">Confirm Password</label>
                <input type="password" name="password2" id="password2" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" placeholder="Confirm your password" required>
            </div>

            <button type="submit" class="w-full bg-red-500 text-white py-2 sm:py-3 rounded-lg hover:bg-red-600 transition duration-300">Register</button>
       
        {% if form.errors %}
            <div class="error-messages bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mt-4">
                <ul class="list-disc pl-5">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
        {% endif %}

        <p class="text-center text-gray-600 mt-6">Already have an account? 
            <a href="{% url 'main:user_login' %}" class="text-red-500 hover:underline">Login</a>
        </p>
    </div>
</div>
{% endblock content %}